services:
  postgres:
    container_name: xlab-routing
    build: .
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: xlab-routing